# Generated by Django 4.2.1 on 2023-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
